# https://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 10.0

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm@6 --global
  - npm ci

test_script:
  - node --version
  - npm --version
  - cmd: "npm test"
